### ISSUE TITLE
Plotting LCA

### ISSUE THREAD

**Issue by dmkahler** [hydro-lab/wind-power#11]
The plotting code is included.  Let me know what you think.

**Comment by dmkahler** [comment]
I added a hard limit of 1.5 to the one with error bars.

**Comment by mkranii** [comment]
Love it! I think it is the right call to cut off at 1.5. I'll add a note in the caption that the Gas DALY goes up to 8.

Also, I'm going to add "Per kWh" to the Y Axis Title.

**Comment by dmkahler** [comment]
Also try an annotation right on the plot:

```
annotate("text", x="Gas", y=1.4, label = "           max=8.45", size = 3) +
```

Note: the spaces are so that it prints next to the bar; you may need to adjust based on how your plot turns out on your computer.

**Comment by dmkahler** [comment]
Ok, I updated, please pull.  To show the combined figure, type the name of the plot's variable into the Consol.
