### ISSUE TITLE
Wind Speed Interpolation

### ISSUE THREAD

**Issue by mkranii** [hydro-lab/wind-power#5]
Need help getting the code right for the slope portion of the code.

**Comment by mkranii** [comment]
https://github.com/hydro-lab/wind-power/blob/12c6b1ee575cefd0629d0df28da6f90ce12c7dd0/windspeed-mean-sds.R

**Comment by mkranii** [comment]
Lines 164, 165, and 166

**Comment by dmkahler** [comment]
I just pushed.  Give it a try.

**Comment by dmkahler** [comment]
You will get a warning, but it is fine - it's just the addition of the "power" column.

**Comment by dmkahler** [comment]
Don't forget to delete line 173.

**Comment by mkranii** [comment]
Ok! So I ran the code and deleted 173.

I'm getting an "m" value of 8.81...which I assume is an average? Because the power curve correlation is not linear....

The next step is to put the wind speed data and the power curve data together, right? I'm not quite sure how to do that, but progress is progress.

**Comment by mkranii** [comment]
https://github.com/hydro-lab/wind-power/commit/f0599cef232f65f5cf22eb49cd29680900782103

**Comment by mkranii** [comment]
Any tips on how to push the wind speed data and the power curve data together?

**Comment by dmkahler** [comment]
The loop creates a new column, a$power.  That is the average power in Watts for the 15 minutes.  @mkranii

**Comment by dmkahler** [comment]
> Ok! So I ran the code and deleted 173.
> 
> 
> 
> I'm getting an "m" value of 8.81...which I assume is an average? Because the power curve correlation is not linear....
> 
> 
> 
> The next step is to put the wind speed data and the power curve data together, right? I'm not quite sure how to do that, but progress is progress. 

The "m" was just the last "m" found.  The output is saved in a$power.

**Comment by dmkahler** [comment]
This appears to be resolved.
