### ISSUE TITLE
Towers Data

### ISSUE THREAD

**Issue by mkranii** [hydro-lab/wind-power#6]
Having trouble changing names, selecting the columns that I'd like to keep, pivoting longer, then pivoting wider, and messing with the timestamp. 

Lines 15-51

Any input is helpful!

**Comment by mkranii** [comment]
https://github.com/hydro-lab/wind-power/blob/9744a7bf134343c9bfc98bf333de2545b028a030/towers

**Comment by dmkahler** [comment]
Updated with file and columns.  Let me know how it goes.  Let's keep this open until after we download the data tomorrow (Thurs 27 Apr 2023).

**Comment by dmkahler** [comment]
@mkranii , how did this work?

**Comment by mkranii** [comment]
I think we fixed everything!

https://github.com/hydro-lab/wind-power/commit/6053f7d44d08b84266115ae6e342f555ec30ac83
