### ISSUE TITLE
Wind Rose issue

### ISSUE THREAD

**Issue by mkranii** [hydro-lab/wind-power#7]
Keep getting an error on line 292. 

https://github.com/hydro-lab/wind-power/commit/53088da4e2d87d0e70275f5ea10654cd2608f09f

**Comment by mkranii** [comment]
Also, looking to generate that monthly energy table for Mellon and Towers? https://github.com/hydro-lab/wind-power/blob/main/WindSpeedDataMay4

**Comment by dmkahler** [comment]
Where are we on this, @mkranii ?

**Comment by mkranii** [comment]
Still getting an error, but now on Line 293. 

Error in if (speed.index > 8) { : missing value where TRUE/FALSE needed

**Comment by dmkahler** [comment]
Assume resolved
